@include('backend.common.fields.image', ['name' => 'image'])
@include('backend.common.fields.text', ['name' => 'name'])
@include('backend.common.fields.text', ['name' => 'email'])
@include('backend.common.fields.text', ['name' => 'phone'])
@include('backend.common.fields.text', ['name' => 'credit'])
@include('backend.common.fields.select', ['name' => 'lawyerType', 'value' => $lawyerTypes])
@include('backend.common.fields.submit')
