@include('backend.common.fields.image', ['name' => 'image'])
@include('backend.common.fields.text', ['name' => 'name'])
@include('backend.common.fields.text', ['name' => 'email'])
@include('backend.common.fields.text', ['name' => 'phone'])
@include('backend.common.fields.submit')
